version: 2.1

jobs:
 
  insalling_apache_EC2_ansible:
    docker:
        - image: python:3.7-alpine3.11

    steps:
      - checkout
      # - add_ssh_keys:
      #        fingerprints: 
      #         - "7e:21:64:03:08:9d:2b:6d:ab:d3:a0:69:ec:c9:f1:2c"
      - add_ssh_keys:
              fingerprints: ["7e:21:64:03:08:9d:2b:6d:ab:d3:a0:69:ec:c9:f1:2c"] 

      - deploy:
          name: Deploy to staging if branch is develop
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              eval `ssh-agent` && ssh-add ~/.ssh/id_rsa* && bundle exec cap staging deploy
            fi

      - run:
          name: Install Ansible
          command: |
            apk add --update ansible

      - run:
          name: Run Playbook and Configure server
          command: |
            cd ~/project/.circleci/ansible
            ansible-playbook main-remote.yml -i ~/project/.circleci/ansible/inventory.txt 

workflows:
  Insalling_Apache_EC2_Ansible-workflow:
    jobs:
      - insalling_apache_EC2_ansible
      