version: 2.1

commands:

  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y

jobs:
 
  insalling_apache_EC2_ansible:
    docker:
        - image: cimg/base:stable

    steps:
      - checkout
      - install_ansible   
      - add_ssh_keys:
             fingerprints: 
              - "7e:21:64:03:08:9d:2b:6d:ab:d3:a0:69:ec:c9:f1:2c"

      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt -vvv ~/project/.circleci/ansible/main-remote.yml

workflows:
  Insalling_Apache_EC2_Ansible-workflow:
    jobs:
      - insalling_apache_EC2_ansible
      